# YOLOArgs
root: "/Download/labelme2yolo"     # Data root directory path. Absolute path.
train_anno: "train2017.txt"   # Directory containing training images. Relative path to 'root'.
val_anno: "val2017.txt"       # Directory containing validation images. Relative path to 'root'.
test_anno: ""             # Optional. Directory containing test images. Relative path to 'root'.
data_anno: "data2017.txt"             # Optional. All images annotation file. Relative path to 'root'.

# number of classes
nc: 80

# class names
names: [ 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
         'hair drier', 'toothbrush' ]
# or text file path containing categories information. One line for one category. Relative path to 'root'.
# names: "names.txt"

# root
# ├── train_anno
# ├── test_anno
# └── val_anno